---
title: "R notebook"
author: "Ying Jhu"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##基本計算
```{r}
5+49
3-4
4*5
1/0
0/0
Inf-Inf
4^5
27%%5  #求餘數
27%/%5  #求商

x=10:30
mean(x)
var(x)

n=1:10
1.25*(n*0.8)-n
```
##例：利息計算
```{r}
intRate=0.01
n=10
principal=1500
payment=principal*intRate/(1-(1+intRate)^(-n))
payment
```

##向量運用
```{r}
x<-c(0,10,20)
number100to200<-100:200
c(number100to200,x)
number100to200[20]
number100to200[c(1:10,30:40)]

x[-3]
x[-1]
x[0]
x[c(0,2)]
```
* x[-10]  x[-c(1,3)]  x[c(-1,3)]錯誤示範
```{r}
c(1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10)%% 2:3
```
##重複與黏貼功能
```{r}
rep(10,5)
rep(seq(11,30,by=3),3)
rep(c(2,3,4),each=3)
rep(seq(11,30,by=3),c(rep(3,3),rep(4,4)))

x=NULL
x[seq(2,20,2)]=seq(1,20,2)
x

x=c(0,10,20)
x/x
1/x

colors=c("brown","yellow","blue")
z=c("brown","yellow",1)
z
substr(colors,1,3)

paste(colors,"candy")
paste0(colors,"candy")
paste0(colors,"-","candy")
paste(colors,c(colors,"red"))
paste(colors,c(colors,"red"),sep=" ")
paste(colors,c(colors,"red"),sep=":")
```
##字母轉數字
```{r}
fac=c("C","B","C","B")
fac=factor(fac)
fac
as.integer(fac)

fac2=c("AAAAAAAAA","ABABABABABABAB","AAAAAAAAAA","BABABABABA",111)
fac2
fac2=factor(fac2)
fac2
as.integer(fac2)

fac3=fac2[-5]
fac3
as.integer(fac3)

fac4=c("AAAAAAAAA","ABABABABABABAB","AAAAAAAAAA","BABABABABA")
fac4
fac4=factor(fac4)
fac4
as.integer(fac4)

levels(fac4)
levels(fac4)[as.integer(fac4)]
levels(fac4)[c(1,2,1,2)]
levels(fac4)[c(1,1,2,1,2,2)]
levels(fac4)[c(1,2,3,1)]
is.na(levels(fac4)[c(1,2,3,1)])
!is.na(levels(fac4)[c(1,2,3,1)])
levels(fac4)[c(1,2,3,1)][!is.na(levels(fac4)[c(1,2,3,1)])]#不會印出false

test=levels(fac4)[c(1,2,3,1)]
test[!is.na(test)]
```
##矩陣
```{r}
m=matrix(20:39,nrow=2,ncol=10)
m
m2=matrix(20:39,nrow=2,ncol=10,byrow=T)
m2
m3=matrix(20:39,nrow=2,ncol=10,byrow=F)
m3

m[2,5]
m[2,]
m[,10]
m[2,c(1,3,5)]
m[c(1,2),c(2,4,6)]
2*m[c(1,2),c(2,4,6)]
m[c(1,2),c(2,4,6)]=2*m[c(1,2),c(2,4,6)]
m
m[c(1,2),c(2,4,6)]=0
m
m[10]
```
##陣列
```{r}
out=array(1:120,c(5,4,3,2))
out
out[,,2,2]
out[c(2,4),c(1,3),2,2]
out[1,1,c(1,2),c(1,2)]
```
##列表
```{r}
x<-c(3,2,3)
y<-c(7,7)
xy=list(xx=x,yy=y)
xy
xy2=list(xx=x,yy=y,xy1=xy)
xy2
```
##數據框
```{r}
color=c("red","red","red1","blue")
number=c(1,3,5,7)
logic=c(T,T,F,F)
out.fr=data.frame(colors=color,numbers=number,logics=logic)
out.fr
out.fr=data.frame(color,number,logics=logic)
out.fr
out.fr[,2]
out.fr[,"number"]
out.fr$number
2*out.fr

```
##時間
```{r}
format(Sys.time(),"%a %b %d %X %Y %Z")
format(Sys.time(),"%H:%M:%OS3")

x<-c("1jan1960","2jan1960","31mar1960","30jul1960")
z<-strptime(x,"%d%b%Y")
x
z

lct<-Sys.getlocale("LC_TIME"); Sys.setlocale("LC_TIME","C")
x<-c("1jan1960","2jan1960","31mar1960","30jul1960")
x
z<-strptime(x,"%d%b%Y")
z

dates<-c("02/27/92","02/27/92","01/14/92","02/28/92","02/01/92")
times<-c("23:03:20","22:29:56","01:03:30","18:21:03","16:56:26")
x<-paste(dates,times)
strptime(x,"%m/%d/%y %H:%M:%S")
x

z<-strptime("20/2/06 11:16:16.683","%d/%m/%y %H:%M:%OS")
z
op<-options(digits.secs=3)
z

strptime("Tue,23 Mar 2010 14:36:38 -0400","%a,%d %b %Y %H:%M:%S %z")
format(seq.Date(as.Date('1978-01-01'),by='day',len=7),"%a")
format(seq.Date(as.Date('2000-01-01'),by='month',len=12),"%b")
format(seq.Date(as.Date('1978-01-03'),by='day',len=10),"%a")
seq(as.Date("2000/1/1"),as.Date("2003/1/1"),by="week")
```
##畫圖
* 直方圖
```{r}
x=c(1:100,201:300)
hist(x)

x<-rnorm(100)
hist(x)
hist(x,breaks=5)
```

* 散布圖
```{r}
x=seq(10,100,5)
y=x^3-2*x
plot(x,y)
plot(x,y,type="l")

x1=(1:300)/100
x2=(301:600)/100
y1=3*x1+2
y2=2*x2-0.5*x2^2
plot(c(x1,x2),c(y1,y2),type="l")

plot(c(0,6),c(-6,11),xlab="x",ylab="y",type="n")

x<-rnorm(100)
y<-rpois(100,30)
mean(y)
plot(x,y,main="Poisson versus Normal")
plot(x,y,type="l")
plot(sort(x),sort(y),type="l")

```

* 曲線圖
```{r}
curve(cos,from=1,to=3*pi)
curve(x^3-2*x,from=1,to=3*pi)

curve((x<=3)*(3*x+2)+(x>3)*(2*x-0.5*x^2),0,6,ylab="y")

curve(3*x+2,0,3,add=T)
curve(2*x-0.5*x^2,3,6,add=T)
```

* 盒鬚圖
```{r}
boxplot(Sepal.Length~Species,data=iris,ylab="Sepal length(cm)",main="Iris measurements",boxwex=0.5)
boxplot(Sepal.Length~Species,data=iris,ylab="Sepal length(cm)",main="Iris measurements",boxwex=0.1)
```

* 長條圖
```{r}
barplot(VADeaths,beside=T,legend=T,ylim=c(0,90),ylab="Deaths per 1000",main="Death rates in Virginia")
```

* 點圖
```{r}
dotchart(VADeaths,xlim=c(0,75),xlab="Deaths per 1000",main="Death rates in Virginia")
```

* 圓餅圖
```{r}
groupsizes<-c(18,30,32,10,10)
labels<-c("甲","乙","丙","丁","戊")
pie(groupsizes,labels,col=c("grey40","white","grey","black","grey50"))
```

* qq-plot
```{r}
X<-rnorm(1000)
D<-exp(rnorm(1000))
qqplot(X,D,main="D is skewed to the right")
```

* 從頭製圖表
```{r}
par(mar=c(5,6,10,7)+0.1)
plot(c(1,9),c(0,50),type="n",xlab="",ylab="") #製成一張無內容圖表

text(6,40,"Plot region")
points(6,20)
text(6,20,"(6,20)",adj=c(0.5,2))
text(6,20,"(6,20)")
mtext(paste("Margin",1:4),side=1:4,line=3)
mtext(paste("Line",0:4),side=1,line=0:4,at=3,cex=0.6)
mtext(paste("Line",0:4),side=2,line=0:4,at=15,cex=0.6)
mtext(paste("Line",0:10),side=3,line=0:10,at=3,cex=0.6)
mtext(paste("Line",0:7),side=4,line=0:7,at=15,cex=0.6)
```

* 利用條件製圖
```{r}
x=3
if (x>2) y=x^2 else y=cos(x)
y

x=1
if (x>2) y=x^2 else y=cos(x)
y

x=1
if (x==2) y=x^2 else y=cos(x)
y

x=1
if (x!=2) y=x^2 else y=cos(x)
y

corplot<-function(x,y,plotit){
 if (plotit==T) plot(x,y)
 cor(x,y)}
corplot(c(1,3,5,7),c(2,2,10,2),F)
corplot(c(1,3,5,7),c(2,2,10,2),T)
```
##函數
* EX1
```{r}
Eratosthenes<-function(n){
if (n>=2){
 sieve<-seq(2,n)
 primes<-c()
 for (i in seq(2,n)){
  if (any(sieve==i)){
   primes<-c(primes,i)
   sieve<-c(sieve[(sieve%%i)!=0],i)}}
 return(primes)
 } else{
 stop("Input value of n should be at  least 2.")}}

n=10
sieve<-seq(2,n)
i=2
sieve==i
any(sieve==i)
sieve%%i
Eratosthenes(10000)
```
* EX2
```{r}
fib1=1
fib2=1
fibonacci=c(fib1,fib2)
while (fib2<300)
{fibonacci=c(fibonacci,fib2)
 oldfib2=fib2
 fib2=fib1+fib2
 fib1=oldfib2}
fibonacci
#一樣
fib1=1
fib2=1
fibonacci=c(fib1,fib2)
while (fib2<300)
{fibonacci=c(fibonacci,fib2)
 n=length(fibonacci)
 fib2=fibonacci[n-1]+fibonacci[n]}
fibonacci
```
* EX3
```{r}
X<-rnorm(100000) #Xi~N(0,1) i=1,2,3...
Y<-rnorm(100000)
Z<-c()
for (i in 1:100000){
 z<-c(Z,X[i]+Y[i])}

z<-rep(NA,100000)
for (i in 1:100000){
 Z[i]<-X[i]+Y[i]}

Z<-X+Y
z1=X*Y
z2=X/Y
z3=log(abs(X))
z4=exp(X-Y)
z5=1/X
z6=sum((X-mean(X))*(Y-mean(Y)))/(length(X)-1)
```
##分配
* 均勻分配
```{r}
runif(10)
runif(10,min=-3,max=10)
```
* 二項分配
```{r}
dbinom(x=4,size=6,prob=0.5)
pbinom(4,6,0.5)
qbinom(0.89,6,0.5)
rbinom(24,15,0.1)
```
* 指數分配
```{r}
rpois(1,1.5*10)

poissonproc<-function(){
 set.seed(10)
 N<-rpois(1,1.5*10)
 P<-runif(N,max=10)
 return(sum(4<=P&P<=5))}
poissonproc()
```
##積分問題
```{r}
set.seed(1)
x=runif(100000)
mean(x^4)

set.seed(1)
x=runif(1000000,min=2,max=5)
mean(sin(x))*(5-2)

set.seed(1)
x=runif(100000,min=1,max=7)
y=runif(100000,3,10)
mean(sin(x-y))*42

set.seed(1)
x=rexp(1000000)
mean(exp(-(x+1)^2)/dexp(x))

set.seed(1)
x=runif(10000000,1,pi)
mean(exp(x))*(pi-1)

set.seed(1)
x=rexp(1000000)
mean(exp(-x))*(pi-1)

set.seed(1)
x=runif(1000000)
y=runif(1000000)
mean(exp(-(y+x)^2)*(x+y)^2)*1
```
##矩陣延伸
```{r}
x = matrix(c(1,2,3,1,4,9),ncol=2)
x
x[,2] #取第2行的數字
rownames(x)
rownames(x) = c("obs1","obs2","obs3")
colnames(x)
colnames(x) = c("x","x2")

y=cbind(seq(1,3),seq(2,4),seq(3,5))   #以column為單位做matrix
y

1/cbind(seq(1,3),seq(2,4),seq(3,5))   #column內所有數字倒數

diag(y) #取出y的對角線
diag(diag(y)) #把1 3 5 放進對角線 變3*3matrix 對角線為1 3 5 其他為0
```
```{r}
x=matrix(1:6,nrow=3)
y=matrix(c(3,4,5,7,7,7),ncol=2)

x*y
x%%y

set.seed(1)
z=matrix(rnorm(9),nrow=3)
solve(z) #回傳反矩陣

#Ax=b
b=c(1,2,3)
A=z
x=solve(A,b)
x
```
##線性規劃
```{r}
f1=function(x){
 ((x[1]-x[2])^2+(x[1]-2)^2+(x[2]-3)^4)/10}
optim(c(1,1),f1)

```
* 錯誤示範
f=function(x,y){((x-y)^2+(x-2)^2+(y-3)^4)/10}
x=seq(0,5,len=20)
y=seq(0,5,len=20)
z=outer(x,y,f)
contour(x,y,z)
optim(c(1,1),f)